CREATE TABLE roles (
   id SERIAL PRIMARY KEY,
   libelle VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
   id SERIAL PRIMARY KEY,
   email VARCHAR(255) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL,
   blocked BOOLEAN NOT NULL DEFAULT false,
   role_id INTEGER NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_user_role FOREIGN KEY (role_id)
      REFERENCES roles(id)
);


CREATE TABLE login_attempts (
   id SERIAL PRIMARY KEY,
   user_id INTEGER NOT NULL,
   attempts INTEGER NOT NULL DEFAULT 0,
   blocked_until TIMESTAMP NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_attempt_user FOREIGN KEY (user_id)
      REFERENCES users(id) ON DELETE CASCADE
);
